version: '3'

services:
  #####################################
  # bold app
  #####################################
  total-trans:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ${BOLD_APP_PATH}:/var/www/html
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ${BOLD_APP_PATH}:/var/www/html
      - ${BOLD_APP_PATH}/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8001:80"
      - "443:443"
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: total-trans
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${BOLD_APP_PATH}/mysql/data:/var/lib/mysql/
      - ${BOLD_APP_PATH}/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


